* {
	Color: #f5f5f5ff;
}

Window {
	BorderWidth: 0;
	BackgroundColor: #494c55ff;
}

Button {
	BorderWidth: 0;
	BackgroundColor: #0f0e13ff;
	Color: #f5f5f5ff;
}

Button:PRELIGHT, CheckButton:PRELIGHT{
	BackgroundColor: #d20537ff;
}

Entry {
	BackgroundColor: #f5f5f5ff;
	Color: #000000ff;
}

CheckButton {
	BorderWidth: 0;
	BackgroundColor: #0f0e13ff;
	CheckColor: #f5f5f5ff;
	CheckSize: 7;
}

CheckButton:ACTIVE {
	BackgroundColor: #f5f5f5ff;
}
